### PR TITLE
Add #include "stdint.h" to please Alpine/Musl?

### PR DESCRIPTION
**Pull request by beberlei**
@andypost can you check about #72 with this PR?

### CODE REVIEW

**Comment by andypost** [comment]
Will check and comment today

**Comment by andypost** [comment]
Checked and it does not solved but
```diff
--- a/timer.h
+++ b/timer.h
@@ -76,6 +76,7 @@
 #endif
         case TIDEWAYS_XHPROF_CLOCK_TSC:
 #if defined(__i386__)
+            ;
             int64_t ret;
             __asm__ volatile("rdtsc" : "=A"(ret));
             return ret;
```
fixed build and extension works

**Comment by beberlei** [comment]
@andypost that makes no sense to me, but ok :-) I tried it another way, can you check?

**Comment by andypost** [comment]
Nice! it works!

**Pull request merged**
